name: Bazel Windows 2022

on:
  push: {}

jobs:
  build_and_test_windows:
    name: VS2022 opt on Windows Server 2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bazel test
        run: |
          bazel --output_base=C:/bazel_output_base test --test_output=errors --config=vs2022 -- //...
